#!/bin/sh
# 99-custom-ip
# 设置 LAN IP 为 192.168.2.1
# heredoc 的 EOF 必须顶格，不能有空格

uci -q batch <<-EOF
	set network.lan.ipaddr='192.168.2.1'
	set network.lan.netmask='255.255.255.0'
	commit network
EOF

exit 0
